title: TheAwesomeCoder05 Builds
author: TheAwesomeCoder05
description: > # this means to ignore newlines until "baseurl:"
  

# social links
github_username:  TheAwesomeCoder05 # DO NOT include the @ character, or else the build will fail!
show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
